import nextEnv from "@next/env";
import postgres from "postgres";
import { readFileSync } from "node:fs";

const { loadEnvConfig } = nextEnv;
loadEnvConfig(process.cwd());
for (const line of readFileSync(".env.development.local", "utf8").split(/\r?\n/)) {
  const match = line.match(/^([^#=]+)=(.*)$/);
  if (match && !process.env[match[1]]) process.env[match[1]] = match[2].replace(/^"|"$/g, "");
}

const connectionString = process.env.RAG_POSTGRES_URL_NON_POOLING || process.env.RAG_POSTGRES_URL;
if (!connectionString) throw new Error("RAG_POSTGRES_URL_NON_POOLING is not configured");

const sql = postgres(connectionString, { max: 1, connect_timeout: 15 });
const statements = [
  "create extension if not exists vector with schema extensions",
  `create table if not exists public.document_chunks (
    id bigint generated by default as identity primary key,
    workspace_id text not null,
    document_name text not null,
    chunk_index integer not null,
    content text not null,
    embedding extensions.vector(768) not null,
    created_at timestamptz not null default now()
  )`,
  "create index if not exists document_chunks_workspace_idx on public.document_chunks (workspace_id)",
  "create index if not exists document_chunks_embedding_idx on public.document_chunks using hnsw (embedding extensions.vector_cosine_ops)",
  `create or replace function public.match_document_chunks (
    query_embedding extensions.vector(768),
    match_workspace_id text,
    match_count integer default 5
  ) returns table (id bigint, document_name text, content text, similarity float)
  language sql stable as $$
    select document_chunks.id, document_chunks.document_name, document_chunks.content,
      1 - (document_chunks.embedding <=> query_embedding) as similarity
    from public.document_chunks
    where document_chunks.workspace_id = match_workspace_id
    order by document_chunks.embedding <=> query_embedding
    limit match_count
  $$`,
];

for (const statement of statements) await sql.unsafe(statement);
await sql.end({ timeout: 5 });
console.log("RAG schema ready");
